---
title: "Parte 2"
output: html_document
date: "2025-12-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(readr)
library(readxl)
library(dplyr)
library(janitor)
data <-  read_excel("IQ_Cancer_Endometrio_merged_NMSP.xlsx")

columnas_diagnostico <- c(
  "edad",
  "imc",
  "tipo_histologico",
  "histo_defin",
  "Grado",
  "grado_histologi",
  "tamano_tumoral",
  "valor_de_ca125",
  "ecotv_infiltsub",
  "metasta_distan",
  "afectacion_linf",
  "AP_centinela_pelvico",
  "AP_ganPelv",
  "p53_molecular",
  "p53_ihq",
  "mut_pole",
  "beta_cateninap",
  "msh2",
  "msh6",
  "pms2",
  "mlh1",
  "grupo_de_riesgo_definitivo",
  "asa"
)


data_diagnostico <- data %>% select(all_of(columnas_diagnostico))


head(data_diagnostico)

```


```{r}

# Calcular frecuencias y porcentajes para todas las columnas
for (col in columnas_diagnostico) {
  cat("\n========================================\n")
  cat("COLUMNA:", col, "\n")
  cat("========================================\n")
  
  # Convertir NA a texto "NA" para que se agrupen todos juntos
  columna_temp <- as.character(data_diagnostico[[col]])
  columna_temp[is.na(columna_temp)] <- "NA"
  
  # Crear tabla de frecuencias
  tabla <- table(columna_temp)
  
  # Calcular porcentajes
  porcentajes <- round((tabla / sum(tabla)) * 100, 2)
  
  # Mostrar valor, frecuencia y porcentaje
  resultado <- data.frame(
    Columna = col,
    Valor = names(tabla),
    Frecuencia = as.numeric(tabla),
    Porcentaje = porcentajes
  )
  
  print(resultado)
  cat("\n")
}
```
#AHORA HACEMOS RATIOS DE EDAD
```{r}

data_diagnostico$edad <- as.numeric(data_diagnostico$edad)
data_diagnostico$grupo_edad <- cut(
  data_diagnostico$edad,
  breaks = c(-Inf, 29, 49, Inf),
  labels = c("0-29", "30-49", "+50")
)

frecuencia_edad <- table(data_diagnostico$grupo_edad)
frecuencia_edad

data.frame(
  Grupo_edad = names(frecuencia_edad),
  Frecuencia = as.numeric(frecuencia_edad),
  Porcentaje = round(as.numeric(prop.table(frecuencia_edad)) * 100, 2)
)
```

